# Generated by Django 3.2.5 on 2022-02-05 18:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_commentmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentmodel',
            name='author_mail',
            field=models.EmailField(default='dafault@default.fr', max_length=254),
        ),
        migrations.AlterField(
            model_name='commentmodel',
            name='post',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='blog.postmodel'),
        ),
    ]
