# Generated by Django 3.2.15 on 2022-09-24 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20220205_1939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentmodel',
            name='author_mail',
            field=models.EmailField(max_length=254),
        ),
    ]
